name: pokedex_manha
description: Pokédex criada para estudos.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  dartz: ^0.9.2
  splashscreen: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.3.2

  flutter_launcher_icons: ^0.8.0

flutter:
  uses-material-design: true

  fonts:
    - family: PokeGoTypes
      fonts:
        - asset: lib/assets/fonts/PokeGOTypes.ttf

    - family: PokemonHollow
      fonts:
        - asset: lib/assets/fonts/PokemonHollow.ttf